config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:index, :create]
  resources :users, only: [:create]

  get 'soon' => 'messages#soon'
  get 'download_file/:filename' => 'messages#download_file', constraints: { filename: /.*/ }, as: :download_file
  get 'close_window' => 'messages#close_window', as: :close_window

  if Rails.env.production? && !ENV["LIVE"]
    root 'messages#soon'
  else
    root 'messages#index'
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  accepts_nested_attributes_for :user

  validates :user_id, presence: true

  after_create { AppMailer.delay.thanks(self) }
  after_create { AppMailer.delay.message_for_the_president(self) }
  after_create { self.delay.add_to_mailchimp_segment }

  def add_to_mailchimp_segment
    begin
      Gibbon::API.lists.subscribe(
        id: ENV["MAILCHIMP_LIST_ID"],
        email: { email: self.user.email },
        merge_vars: {
          FNAME: self.user.first_name,
          LNAME: self.user.last_name
        },
        double_optin: false,
        update_existing: true
      )
      Gibbon::API.lists.static_segment_members_add(
        id: ENV["MAILCHIMP_LIST_ID"],
        seg_id: ENV["MAILCHIMP_MESSAGES_SEG_ID"],
        batch: [{ email: self.user.email }]
      )
    rescue Exception => e
      Rails.logger.error e
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  def name
    "#{first_name} #{last_name}"
  end

  def student?
    role == 'student'
  end

  def teacher?
    role == 'teacher'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @user = User.new
    @message = Message.new
    @message.build_user
  end

  def create
    user_params = message_params[:user_attributes]
    user = User.create_with(user_params).find_or_create_by(email: user_params[:email])

    # if no message was sent today by the user
    if Message.where(user: user).where('created_at >= ?', Date.today).empty?
      Message.create(user: user)
      redirect_to root_path(anchor: 'compartilhe')
    else
      redirect_to root_path(anchor: 'email-ja-enviado')
    end
  end

  def soon
    render layout: 'static'
  end

  def close_window
    render layout: 'static'
  end

  def download_file
    send_file "#{Rails.root}/public/materials/#{params[:filename]}"
  end

  private
  def message_params
    params.fetch(:message, {}).permit(user_attributes: [:first_name, :last_name, :email])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    user = User.find_by(email: user_params[:email])

    if user.nil?
      user = User.create(user_params)
    else
      user.update(user_params)
    end

    if user.save
      AppMailer.delay.user_registered(user)
      redirect_to root_path(anchor: 'obrigado')
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :role, :school, :age, :state, :city, :area_code, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def brazilian_states
    [
      ['AC', 'AC'],
      ['AL', 'AL'],
      ['AM', 'AM'],
      ['AP', 'AP'],
      ['BA', 'BA'],
      ['CE', 'CE'],
      ['DF', 'DF'],
      ['ES', 'ES'],
      ['GO', 'GO'],
      ['MA', 'MA'],
      ['MG', 'MG'],
      ['MS', 'MS'],
      ['MT', 'MT'],
      ['PA', 'PA'],
      ['PB', 'PB'],
      ['PE', 'PE'],
      ['PI', 'PI'],
      ['PR', 'PR'],
      ['RJ', 'RJ'],
      ['RN', 'RN'],
      ['RO', 'RO'],
      ['RR', 'RR'],
      ['RS', 'RS'],
      ['SC', 'SC'],
      ['SE', 'SE'],
      ['SP', 'SP'],
      ['TO', 'TO']
    ]
  end
end

app/views/layouts/_facebook_sdk.html.slim
#fb-root
javascript:
  window.fbAsyncInit = function() {
    FB.init({
      appId   : #{ENV["FACEBOOK_APP_ID"]},
      xfbml   : true,
      version : 'v2.4'
    });
  };

  (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.4";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/layouts/signed_mail.html.slim
= yield

= image_tag attachments['assinatura-email-gut.png'].url

app/views/messages/_slide_11.html.slim
.slide-11.bg-black
  .container.py4
    .clearfix
      .col-10.md-col-6.mx-auto.mb4
        h1.white.center.mt0 ESPALHE POR AÍ
        h2.cta.blue.mb4.center Quanto mais gente entrar para a nossa mobilização, maiores são as chances de vitória!
      .col-12.md-col-10.mx-auto.center
        = link_to image_tag('slide-11-facebook.png', class: 'px2'),
        "https://www.facebook.com/dialog/share?\
          app_id=#{ENV['FACEBOOK_APP_ID']}\
          &display=popup\
          &href=#{URI::encode(root_url)}\
          &redirect_uri=#{URI::encode(close_window_url)}", class: 'facebook-share-button'
        = link_to image_tag('slide-11-twitter.png', class: 'px2'), "https://twitter.com/intent/tweet?url=#{URI::encode('http://internetnaescola.org/')}&hashtags=internetnaescola&text=#{URI::encode('Junte-se a milhares de pessoas por uma internet rápida em todas as escolas públicas do país')}", class: 'twitter-share-button'

app/views/messages/_slide_12.html.slim
#espalhe.slide-12.border-bottom
  .container.py4
    .col-10.md-col-8.lg-col-6.mx-auto
      h1.center(title='http://www.internetnaescola.org/#espalhe') MATERIAIS DE MOBILIZAÇÃO
      h2.cta.gray.mb3.center Faça o download dos nossos materiais de mobilização e espalhe por aí nossa mensagem.
    .clearfix.mxn2
      .col.col-12.md-col-3.p2.center
        .col-5.mx-auto.items= image_tag('slide-12-1.png')
        .items-secondary
          h3.col-10.mx-auto.mt0.mb1 Cartazes
        .items-terciary.mb1
          p.col-10.mx-auto.gray Pra você pendurar na sua escola, bairro ou cidade
        = link_to 'Ver todos', '#cartazes', class: ['btn', 'btn-primary', 'rounded', 'col-6', 'py1', 'bg-blue', 'smooth']
        .md-hide.py3
      .col.col-12.md-col-3.p2.center
        .col-6.mx-auto.items= image_tag('slide-12-2.png', class: 'py2', style: 'margin-top: 13px;')
        .items-secondary
          h3.col-10.mx-auto.mt0.mb1 Banners web
        .items-terciary.mb1
          p.col-10.mx-auto.gray Pra você que tem um site e quer apoiar a campanha
        = link_to 'Ver todos', '#banners', class: ['btn', 'btn-primary', 'rounded', 'col-6', 'py1', 'bg-blue', 'smooth']
        .md-hide.py3
      .col.col-12.md-col-3.p2.center
        .col-6.mx-auto.items= image_tag('slide-12-3.png', class: 'py2', style: 'margin-top: 10px;')
        .items-secondary
          h3.col-10.mx-auto.mt0.mb1 Adesivos
        .items-terciary.mb1
          p.col-10.mx-auto.gray Pra você colar por aí a mensagem da mobilização
        = link_to 'Ver todos', '#adesivos', class: ['btn', 'btn-primary', 'rounded', 'col-6', 'py1', 'bg-blue', 'smooth']
        .md-hide.py3
      .col.col-12.md-col-3.p2.center
        .col-6.mx-auto.items= image_tag('slide-12-4.png', class: 'py2', style: 'margin-top: 10px;')
        .items-secondary
          h3.col-10.mx-auto.mt0.mb1 Plano Técnico
        .items-terciary.mb1
          p.col-10.mx-auto.gray Documento que aponta os possíveis caminhos
        = link_to 'Baixe aqui', download_file_path('sumario-escolas-conectadas.pdf'), class: ['btn', 'btn-primary', 'rounded', 'col-6', 'py1', 'bg-blue']
        .md-hide.py3
  .display-none
    #cartazes.remodal data-remodal-id="cartazes"
      .container
        .col-12.popup-header.bg-blue
          button.remodal-close data-remodal-action="close"
          = image_tag('header-cartazes.png', class: 'mt1')
        .col-10.md-col-8.lg-col-6.mx-auto
          h1.mt4.mb0.center CARTAZES
          h4.cta.gray.mt0.mb2.center Clique na imagem para baixar seu cartaz favorito

        .col-11.mx-auto
          .col.lg-col-1.lg-show &nbsp;
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_vermelho_1.png'), download_file_path('cartaz_vermelho_1.pdf')
            h5.regular.mt0.mb2.gray Cartaz 01 A4 Vermelho
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_vermelho_2.png'), download_file_path('cartaz_vermelho_2.pdf')
            h5.regular.mt0.mb2.gray Cartaz 02 A4 Vermelho
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_vermelho_3.png'), download_file_path('cartaz_vermelho_3.pdf')
            h5.regular.mt0.mb2.gray Cartaz 03 A4 Vermelho
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_vermelho_4.png'), download_file_path('cartaz_vermelho_4.pdf')
            h5.regular.mt0.mb2.gray Cartaz 04 A4 Vermelho
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_vermelho_5.png'), download_file_path('cartaz_vermelho_5.pdf')
            h5.regular.mt0.mb2.gray Cartaz 05 A4 Vermelho
          .col.lg-col-1.lg-show &nbsp;
          .clearfix.lg-show
          .col.lg-col-1.lg-show &nbsp;
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_azul_1.png'), download_file_path('cartaz_azul_1.pdf')
            h5.regular.mt0.mb2.gray Cartaz 01 A4 Azul
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_azul_2.png'), download_file_path('cartaz_azul_2.pdf')
            h5.regular.mt0.mb2.gray Cartaz 02 A4 Azul
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_azul_3.png'), download_file_path('cartaz_azul_3.pdf')
            h5.regular.mt0.mb2.gray Cartaz 03 A4 Azul
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_azul_4.png'), download_file_path('cartaz_azul_4.pdf')
            h5.regular.mt0.mb2.gray Cartaz 04 A4 Azul
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_azul_5.png'), download_file_path('cartaz_azul_5.pdf')
            h5.regular.mt0.mb2.gray Cartaz 05 A4 Azul
          .col.lg-col-1.lg-show &nbsp;
          .clearfix.lg-show
          .col.lg-col-1.lg-show &nbsp;
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_preto_1.png'), download_file_path('cartaz_preto_1.pdf')
            h5.regular.mt0.mb2.gray Cartaz 01 A4 Preto
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_preto_2.png'), download_file_path('cartaz_preto_2.pdf')
            h5.regular.mt0.mb2.gray Cartaz 02 A4 Preto
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_preto_3.png'), download_file_path('cartaz_preto_3.pdf')
            h5.regular.mt0.mb2.gray Cartaz 03 A4 Preto
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_preto_4.png'), download_file_path('cartaz_preto_4.pdf')
            h5.regular.mt0.mb2.gray Cartaz 04 A4 Preto
          .col.col-6.md-col-4.lg-col-2
            = link_to image_tag('cartaz_preto_5.png'), download_file_path('cartaz_preto_5.pdf')
            h5.regular.mt0.mb2.gray.mb4 Cartaz 05 A4 Preto
          .col.lg-col-1.lg-show &nbsp;


    #banners.remodal data-remodal-id="banners"
      .container
        .col-12.popup-header.bg-blue
          button.remodal-close data-remodal-action="close"
          = image_tag('header-banners.png', class: 'mt1')
        .col-10.md-col-8.lg-col-6.mx-auto
          h1.mt4.mb0.center BANNERS WEB
          h4.cta.gray.mt0.mb2.center Clique no seu banner favorito para baixá-lo

        .col-11.md-col-9.mx-auto.mxn2
          .col.col-12.md-col-6.px2
            = link_to image_tag('banner1.png'), download_file_path('bannerweb_300x250_internetnaescola_v1.gif')
            h5.regular.mt0.mb2.gray Banner 01 - 300x250px
          .col.col-12.md-col-6.px2
            = link_to image_tag('banner2.png'), download_file_path('bannerweb_300x250_internetnaescola_v2.gif')
            h5.regular.mt0.mb2.gray Banner 02 - 300x250px
          .col.col-12.px2
            = link_to image_tag('banner3.png'), download_file_path('bannerweb_728x90_internetnaescola_v1.gif')
            h5.regular.mt0.mb2.gray Banner 03 - 728x90px
          .col.col-12.px2
            = link_to image_tag('banner4.png'), download_file_path('bannerweb_728x90_internetnaescola_v2.gif')
            h5.regular.mt0.mb2.gray Banner 04 - 728x90px
          .col-8.mx-auto.px2
            = link_to image_tag('banner5.png'), download_file_path('bannerweb_468x60_internetnaescola_v1.gif')
            h5.regular.mt0.mb2.gray Banner 05 - 468x60px
          .col-8.mx-auto.px2
            = link_to image_tag('banner6.png'), download_file_path('bannerweb_468x60_internetnaescola_v2.gif')
            h5.regular.mt0.mb2.gray.mb4 Banner 06 - 468x60px

    #adesivos.remodal data-remodal-id="adesivos"
      .container
        .col-12.popup-header.bg-blue
          button.remodal-close data-remodal-action="close"
          = image_tag('header-adesivos.png', class: 'mt1')
        .col-10.md-col-8.lg-col-6.mx-auto
          h1.mt4.mb0.center ADESIVOS
          h4.cta.gray.mt0.mb2.center Clique no seu adesivo favorito para baixá-lo

        .col-11.mx-auto.mxn2
          .col.col-12.md-col-4.px2
            = link_to image_tag('adesivo_vermelho.png'), download_file_path('adesivo_vermelho_internetnaescola.pdf')
            h5.regular.mt0.mb2.gray Adesivo 01 Vermelho
          .col.col-12.md-col-4.px2
            = link_to image_tag('adesivo_azul.png'), download_file_path('adesivo_azul_internetnaescola.pdf')
            h5.regular.mt0.mb2.gray Adesivo 02 Azul
          .col.col-12.md-col-4.px2
            = link_to image_tag('adesivo_branco.png'), download_file_path('adesivo_branco_internetnaescola.pdf')
            h5.regular.mt0.mb2.gray.mb4 Adesivo 03 Branco

app/views/messages/_slide_8.html.slim
#teste.slide-8.bg-red
  .container.py4
    .clearfix
      .col-10.md-col-8.lg-col-6.mx-auto
        .clearfix
          .col.col-12.md-col-3.center
            = image_tag('slide-8-header.png')
          .col.col-12.md-col-9.p2.center.md-left-align
            h3.inline.stroke.border.border-maroon.rounded.m0.py1.px2.maroon MISSÃO 2
            h1.lh2.mb0.maroon(title='http://www.internetnaescola.org/#teste') TESTE A INTERNET NA SUA ESCOLA.
      .col-10.md-col-8.lg-col-7.mx-auto.center
        h3.regular.maroon Faça o teste de velocidade e descubra como está a conexão da sua escola. É rápido, automático e você pode fazer muitas vezes.
      .col-12.md-col-10.mx-auto.center.responsive-embed.mb2
        .iframe-container
          iframe.fit src="http://54.207.215.75/partners/index.html?partner" width="720px" height="520px" frameborder="0"
      .col-10.md-col-8.lg-col-7.mx-auto.center
        h3.regular.maroon.mb3
          | Como é feita a medição da velocidade de internet? &nbsp;
          = link_to '#como-funciona-teste', class: ['underline', 'maroon'] do
            | Saiba mais.
      .col-12.md-col-10.mx-auto.center
        = link_to image_tag('slide-11-facebook.png', class: 'px2 mb2'),
        "https://www.facebook.com/dialog/feed?\
          app_id=#{ENV['FACEBOOK_APP_ID']}\
          &display=popup\
          &href=#{URI::encode(root_url(anchor: 'teste'))}\
          &name=#{URI::encode('Teste a internet da sua escola')}\
          &description=#{URI::encode('Junte-se a milhares de pessoas para mostrar que a internet nas escolas não é suficiente para o acesso a conteúdos educativos de qualidade. Em menos de um minuto, você ajuda a transformar a educação em nosso país!')}\
          &link=#{URI::encode(root_url(anchor: 'teste'))}\
          &picture=#{URI::encode(image_url('fb-test-share.jpg'))}\
          &redirect_uri=#{URI::encode(close_window_url)}", class: 'facebook-share-button'
        = link_to image_tag('slide-11-twitter.png', class: 'px2 mb2'), "https://twitter.com/intent/tweet?url=#{URI::encode('http://internetnaescola.org/#teste')}&hashtags=internetnaescola&text=#{URI::encode('Qual a velocidade da internet na sua escola? Faça o teste e ajude a melhorar as escolas brasileiras')}", class: 'twitter-share-button'

#mapa
  .container.py4
    .col-10.md-col-8.lg-col-6.mx-auto
      h1.white.mt0.center(title='http://www.internetnaescola.org/#mapa') MAPA DA CONECTIVIDADE
      h2.cta.white.mb3.center Veja, por estado, as escolas que já testaram sua velocidade de conexão.
    .clearfix
      .col-10.md-col-8.mx-auto
        = javascript_include_tag('https://public.tableau.com/javascripts/api/viz_v1.js')
        .tableauPlaceholder style='height: 742px;'
          <noscript>
            <a href='#'><img alt='DESAFIO DA CONECTIVIDADE ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Ma&#47;Mapa-TestesdeVelocidade&#47;MapadaConectividade&#47;1_rss.png' style='border: none' /></a>
          </noscript>
          <object class='tableauViz' width='100%' height='742' style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='site_root' value='' /><param name='name' value='Mapa-TestesdeVelocidade&#47;MapadaConectividade' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Ma&#47;Mapa-TestesdeVelocidade&#47;MapadaConectividade&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='showVizHome' value='no' /><param name='showTabs' value='y' /><param name='bootstrapWhenNotified' value='true' /></object>

.display-none
  #como-funciona-teste.remodal data-remodal-id="como-funciona-teste"
    .container
      .col-12.popup-header.bg-red
        button.remodal-close data-remodal-action="close"
      .col-10.mx-auto.p3.left-align
        h3.py2 Como é feita a medição da velocidade de internet?

        .border-top.border-bottom.py2.mb2
          p Você pode estar se perguntando por que outros testes de velocidade apresentam um resultado maior do que o teste www.internetnaescola.org. A resposta é que os testes podem aferir a velocidade de modo diferente.

          p Muitos testes aferem a velocidade da última milha de conexão, ou seja, se aquela que você contratou está sendo entregue. Um exemplo: “Contratei 10MEGA e medi que a velocidade que está sendo entregue é de 8MEGA”. Mas como esses MEGAS são utilizados dentro da escola?

          p Bom, é isso que nós estamos tentando medir: quão veloz é a conexão quando um usuário está acessando a Internet. Nosso teste avalia qual a velocidade da sua internet para acessar os conteúdos disponíveis online. E isso depende tanto de onde está armazenado este conteúdo (servidores) quanto do número de usuários conectados na rede ao mesmo tempo que você.

          p O resultado do teste de velocidade pode variar dependendo do número de pessoas que estão conectadas naquela internet no momento em que você está realizando o teste. Essa é uma medida mais real, uma vez que a conexão de internet de uma escola varia ao longo do dia de acordo com o número de alunos e professores que estão nela conectados.

          p Agora você já sabe: estamos medindo a sua experiência em navegar pela internet, pois é assim que funciona na maioria das escolas: compartilhamos a conexão. Com isso, buscamos uma medida mais real de qual velocidade você tem disponível.

          p Entendeu a importância? Agora complete os 10 testes e convide outras escolas a fazerem o mesmo!

app/views/messages/_slide_9.html.slim
#participe.slide-9.bg-blue
  .container.py4
    .clearfix
      .col-10.md-col-8.lg-col-6.mx-auto
        .clearfix
          .col.col-12.md-col-3.center
            = image_tag('slide-9-header.png')
          .col.col-12.md-col-9.p2.center.md-left-align
            h3.inline.stroke.border.border-navy.rounded.m0.py1.px2.navy MISSÃO 3
            h1.lh2.mb0.navy DIA DA CONECTIVIDADE
      .col-10.md-col-8.mx-auto.center
        h3.regular.white.mb3 Seja um puxador do Bonde da Conexão. Organize o Dia da Conectividade na sua escola. No dia 30/11, internet, cultura e diversão, simultaneamente, em várias escolas do país. Você vai precisar:
      .clearfix.col-10.md-col-8.mx-auto
        .col.col-2.px1.right-align
          = image_tag('slide-9-checkbox.png')
        .col.col-10.px2
          h3.white.mt0.mb1 Falar bastante com a gente
          p.white.mb3 Vamos te mandar ideias para você agitar e materiais sobre como envolver sua escola. Nós vamos estar ao seu lado para te inspirar e te ajudar.
        .col.col-2.px1.right-align
          = image_tag('slide-9-checkbox.png')
        .col.col-10.px2
          h3.white.mt0.mb1 Falar com todo mundo
          p.white.mb3 Ninguém faz nada sozinho. Se você é aluno, escolha um professor bem bacana pra te ajudar. Se você é educador, agite seus alunos!
        .col.col-2.px1.right-align
          = image_tag('slide-9-checkbox.png')
        .col.col-10.px2
          h3.white.mt0.mb1 Fazer um pouco, junto com muitos!
          p.white.mb4 Serão muitas vozes em escolas de todo o país. Cada um fazendo sua parte para espalharmos nossa mensagem pelo Brasil! \o/

        .col-10.mx-auto.center.mxn2
          h3.mb3.white Inscreva-se para receber todas as informações.
          = link_to 'SOU ALUNO', '#cadastro', data: { role: 'student' }, class: ['btn', 'btn-primary', 'rounded', 'py1', 'm2', 'col-8', 'md-col', 'md-col-5', 'bg-navy', 'data-role-link']
          = link_to 'SOU EDUCADOR', '#cadastro', data: { role: 'teacher' }, class: ['btn', 'btn-primary', 'rounded', 'py1', 'm2', 'col-8', 'md-col', 'md-col-5', 'bg-navy', 'data-role-link']

  #cadastro.remodal data-remodal-id="cadastro"
    .container
      .col-12.popup-header.bg-blue
        button.remodal-close data-remodal-action="close"
        = image_tag('slide-9-header.png', class: 'mt1')
      .py3
        .col-10.mx-auto.center
          h2 Nosso bonde está prestes a partir!
          p.gray Que legal que você quer puxar o Bonde da Conexão na sua escola. Deixe seu contato para a gente te mandar os próximos passos dessa ação. Se você usar Whatsapp, fica ainda mais fácil trocar ideias.
        .col-10.mx-auto.center
          = form_for(@user, class: 'mnx2') do |f|
            = f.hidden_field(:role, id: :user_role)
            .clearfix
              .col.col-12.md-col-6.mx-auto.px1
                = f.text_field(:first_name, placeholder: 'Nome*', required: true, class: ['field', 'col-12'])
              .col.col-12.md-col-6.mx-auto.px1
                = f.text_field(:last_name, placeholder: 'Sobrenome*', required: true, class: ['field', 'col-12'])
            .clearfix
              .col.col-12.mx-auto.px1
                = f.text_field(:school, placeholder: 'Escola*', required: true, class: ['field', 'col-12'])
            .clearfix
              .col.col-8.md-col-9.mx-auto.px1
                = f.email_field(:email, placeholder: 'E-mail*', required: true, class: ['field', 'col-12'])
              .col.col-4.md-col-3.mx-auto.px1
                = f.number_field(:age, placeholder: 'Idade*', required: true, class: ['field', 'col-12'])
            .clearfix
              .col.col-4.md-col-3.mx-auto.px1
                = f.select(:state, options_for_select(brazilian_states), { prompt: 'Estado*' }, required: true, class: ['field', 'col-12'])
              .col.col-8.md-col-9.mx-auto.px1
                = f.text_field(:city, placeholder: 'Cidade*', required: true, class: ['field', 'col-12'])
            .clearfix
              .col.col-4.md-col-3.mx-auto.px1
                = f.text_field(:area_code, placeholder: 'DDD', class: ['field', 'col-12'])
              .col.col-8.md-col-9.mx-auto.px1
                = f.phone_field(:phone, placeholder: 'Whatsapp / Celular', class: ['field', 'col-12'])
            .clearfix
              .col-12.mx-auto.left-align.mb3
                span.gray.px1 * Campo obrigatório
            .col-12.mx-auto
              = f.submit 'ENVIAR', class: ['btn', 'btn-primary', 'bg-blue', 'rounded', 'col-8']

  #obrigado.remodal data-remodal-id="obrigado"
    .container
      .col-12.popup-header.bg-blue
        button.remodal-close data-remodal-action="close"
        = image_tag('slide-9-header.png', class: 'mt1')
      .py3.center
        .col-10.mx-auto
          h2 Oba, já estamos juntos!
          p.gray Vamos entrar em contato com você. ;)
        .col-12.mx-auto
          = link_to image_tag('slide-11-facebook.png', class: 'px2'),
          "https://www.facebook.com/dialog/share?\
            app_id=#{ENV['FACEBOOK_APP_ID']}\
            &display=popup\
            &href=#{URI::encode(root_url)}\
            &redirect_uri=#{URI::encode(close_window_url)}", class: 'facebook-share-button'
          = link_to image_tag('slide-11-twitter.png', class: 'px2'), "https://twitter.com/intent/tweet?url=#{URI::encode('http://internetnaescola.org/')}&hashtags=internetnaescola&text=#{URI::encode('Junte-se a milhares de pessoas por uma internet rápida em todas as escolas públicas do país')}", class: 'twitter-share-button'